### ISSUE TITLE
I think the weight should be initialized as 0 rather than 0.5

### ISSUE THREAD

**Issue by ToTheBeginning** [4uiiurz1/pytorch-deform-conv-v2#10]
https://github.com/4uiiurz1/pytorch-deform-conv-v2/blob/9ccc492a37db946b57fe049d6f9f6ef54e8e6426/deform_conv_v2.py#L25

**Comment by 4uiiurz1** [comment]
In the paper, "Thus, the initial values of ∆pk and ∆mk are 0 and 0.5, respectively. "

**Comment by ToTheBeginning** [comment]
You may forget about the sigmoid :)

**Comment by ToTheBeginning** [comment]
> In the paper, "Thus, the initial values of ∆pk and ∆mk are 0 and 0.5, respectively. "

You may forget about the sigmoid :)

**Comment by 4uiiurz1** [comment]
I see. You are right. 
The modulated weight should be initialized as 0.
Thanks for letting me know!
i'll fix it!

**Comment by jszgz** [comment]
@ToTheBeginning Hello, can you review my [issue ](https://github.com/4uiiurz1/pytorch-deform-conv-v2/issues/21) ? I think the bilinear kernel is wrong
