### ISSUE TITLE
Meaning of q_lt, q_rb, q_lb, q_rt?

### ISSUE THREAD

**Issue by zjplab** [4uiiurz1/pytorch-deform-conv-v2#15]
I know roughly these variables represent some kind of boundary coordinates.  But what on earth do they represent? What does "lt" "rb" mean exactly?

**Comment by zjplab** [comment]
lt: **upper left**
rb:  **bottom right**

**Comment by jszgz** [comment]
> lt: **upper left**
> rb: **bottom right**

Hello, do you now what does 
```
        q_lb = torch.cat([q_lt[..., :N], q_rb[..., N:]], dim=-1)
        q_rt = torch.cat([q_rb[..., :N], q_lt[..., N:]], dim=-1)
```
mean ? what did `self._get_p` do? Why `q_rb = q_lt + 1`?
