### ISSUE TITLE
Confused with edge value.

### ISSUE THREAD

**Issue by youansheng** [4uiiurz1/pytorch-deform-conv-v2#3]
https://github.com/4uiiurz1/pytorch-deform-conv-v2/blob/918742a21cdad33ae73cad43ca7db4f14d1a8986/deform_conv_v2.py#L64

Why not the value of edge position in the padding area is not computed by bilinear interpolation, instead of sampling the floor-position value?

**Comment by 4uiiurz1** [comment]
I don't understand that problem well so can you explain it in detail?
